### PR TITLE
Update NHS promo image on homepage

### PR DESCRIPTION
**Pull request by andysellick**
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

## What / why

Update the homepage NHS promo box image, link and description.

## Visual changes

Before:

Screenshot 2021-05-06 at 13 30 16

After:

Screenshot 2021-05-06 at 13 30 20

Trello card: https://trello.com/c/feKGqFbt/350-replace-nhs-app-promo-box-on-govuk-homepage

### CODE REVIEW

**Comment by kevindew** [comment]
Thanks @andysellick change looks good. I've just a question and a couple of minor things. 

I understand the original image is a PNG, is it preferable to have this resized multiple times as a JPG compared to the single PNG approach that we have for the Hands/Face/Space image: https://github.com/alphagov/frontend/blob/f0b2893d442812a9888315ce9d288f33000ecbe5/app/views/homepage/index.html.erb#L93-L100 ? The PNG would seem to perhaps offer lower file sizes and crisper rendering from my vague recollections.

Minor things: the image sizing guidance has changed for a large image to be 610 wide as per: https://github.com/alphagov/frontend/blob/f0b2893d442812a9888315ce9d288f33000ecbe5/app/assets/images/homepage/_README.md and I think it might be worth renaming the image files as I don't think the name of NHS app quite captures the content.

**Comment by andysellick** [comment]
PNG vs JPG - good question, I've raised a semi-duplicate PR to test this (https://github.com/alphagov/frontend/pull/2752). The PNG is fractionally clearer, and comes out at `20KB`. For JPG, the largest file (600w) is `25KB`, but the rest are `19KB` or smaller. The PNG approach is simpler, but the JPG approach seems to offer the better download size across the board. Unsure, will have a think.

Image sizing guidance - it does say 610px, but as far as I can tell the largest possible size the image could be displayed at is 600px (which is at the tablet breakpoint) so I don't know why that is?

Renaming - yes, will do that once we decide whether PNG or JPG is better.

**Comment by kevindew** [comment]
> PNG vs JPG - good question, I've raised a semi-duplicate PR to test this (#2752). The PNG is fractionally clearer, and comes out at `20KB`. For JPG, the largest file (600w) is `25KB`, but the rest are `19KB` or smaller. The PNG approach is simpler, but the JPG approach seems to offer the better download size across the board. Unsure, will have a think.

Sure, I'm happy with whichever you decide. My vote (if you end up stuck) would be for simpler PNG.

> Image sizing guidance - it does say 610px, but as far as I can tell the largest possible size the image could be displayed at is 600px (which is at the tablet breakpoint) so I don't know why that is?

Oh dear, it looks like I left a crappy commit message for that: https://github.com/alphagov/frontend/commit/2288c4b395e7cedee4ed60c57c8f59c1f3292a9b 🤦  I worked with Ian to learn about why it was previously 608 and I should have documented it better.

From looking back (maybe we'll want to include this on the _README.md?). The features are within `.govuk-grid-column-one-third` elements that, at viewport width <= 640px, switch to width 100% with 15px horizontal padding. Subtracting the 15px x 2 from the 640 leaves the magic 610px number.

If you resize your browser to 640 you can see how the one with a 610px size (the budget) fills the element whereas the 600px ones have some spacing on the right.

> 
> Renaming - yes, will do that once we decide whether PNG or JPG is better.

👍

**Comment by andysellick** [comment]
Ah yes I see it now, thanks.

Right, I think I'm going to give up on this PR and go with https://github.com/alphagov/frontend/pull/2752 instead. PNG might not offer the best image size for everyone, but the visual is cleaner and 20Kb isn't terrible.

**Pull request closed without merging**
