### PR TITLE
Upgrade govuk-frontend-toolkit

### PR DESCRIPTION
**Pull request by binaryberry**
This will allow to have the latest analytics functionality.

All tests pass, I pushed the branch to integration and everything seems normal.

[Trello](https://trello.com/c/mGibNI4w/420-upgrade-frontend-to-the-latest-version-of-govuk-frontend-toolkit-small)

### CODE REVIEW

**Comment by boffbowsh** [comment]
👍  but don't merge until Fri 10th June

**Comment by dsingleton** [comment]
There's quite a few changes between these version: https://github.com/alphagov/govuk_frontend_toolkit/compare/v4.1.1...v4.12.0

Before merging we i'd recommend checking the `CHANGELOG` for upgrade notes: https://github.com/alphagov/govuk_frontend_toolkit/blob/master/CHANGELOG.md#411

**Comment by nickcolley** [comment]
Reviewed the [live examples](https://github.com/alphagov/frontend#live-examples), code diff, and changelog.

LGTM 👍

**Comment by boffbowsh** [comment]
DNM removed. Merge it if you're happt @nickcolley

**Comment by nickcolley** [comment]
I think we need to deploy Static before we can merge this as we need a newer version of govuk_template, https://github.com/alphagov/static/blob/release_2386/Gemfile#L48

**Comment by dsingleton** [comment]
👍 from me, the [only uses](https://github.com/alphagov/frontend/search?l=scss&q=%22include+button%22&type=Code&utf8=%E2%9C%93) of the FET `button` mixin are for styles that aren't used anymore - secondary buttons on custom start pages, that [aren't referenced by markup](https://github.com/alphagov/frontend/search?utf8=%E2%9C%93&q=button-secondary) anymore.

**Comment by nickcolley** [comment]
Thanks all 👍  👀

**Pull request merged**
