### PR TITLE
Remove Directgov Businesslink branding

### PR DESCRIPTION
**Pull request by camilleldn**
:hocho: :hocho: :hocho: 

https://www.agileplannerapp.com/boards/105200/cards/9078

Linked to:
https://github.com/alphagov/static/pull/518
https://github.com/alphagov/whitehall/pull/1935

### CODE REVIEW

**Comment by JordanHatch** [comment]
:hocho: :+1:

**Comment by bradleywright** [comment]
Do we need to wait for anything before merging this? Or can I just merge?

**Comment by camilleldn** [comment]
@bradleywright mergeable as is :)

**Comment by edds** [comment]
Can we also remove the image assets ( [1](https://github.com/alphagov/frontend/blob/74deffba/app/assets/images/homepage/businesslink-logo-2x.png), [2](https://github.com/alphagov/frontend/blob/74deffba/app/assets/images/homepage/businesslink-logo.png), [3](https://github.com/alphagov/frontend/blob/74deffba/app/assets/images/homepage/directgov-logo-2x.png), [4](https://github.com/alphagov/frontend/blob/74deffba/app/assets/images/homepage/directgov-logo.png) )  please.

**Pull request merged**
