### PR TITLE
Remove open in new window feature for transactions

### PR DESCRIPTION
**Pull request by nickcolley**
Proposal to remove this so we don't need to add it as a feature when consuming the [button component](https://govuk-static.herokuapp.com/component-guide/button/start_now_button_with_info_text)

It's not clear why this was added, but it's wildly inconsistent since we don't seem to be updating it.

Be good to get any input in on if this is a good idea to remove.

Originally added in https://github.com/alphagov/frontend/pull/43

### CODE REVIEW

**Comment by fofr** [comment]
Got a failing test:
```
1) Failure:
TransactionTest#test_: a transaction which should open in a new window should have the correct target attribute set on the 'Start now' link for a new window.
/test/integration/transaction_test.rb:84:
Expected false to be truthy.
```

**Comment by fofr** [comment]
I approve of this change. It's weird when links that look the same do different things.

**Comment by alextea** [comment]
From what I remember these were transactions on external sites – old directgov or local council transactions.

**Comment by nickcolley** [comment]
Given that we do not add to this behaviour for new external sites, I think this makes sense to remove.

This'll mean the start now buttons have a consistent behaviour and avoid any potential accessibility issues associated with opening links in a new window.

**Comment by keithiopia** [comment]
Like @alextea says - I've got a vague recollection of this being done to cater for legacy services, but I see no reason to keep it.

**Pull request merged**
