### PR TITLE
Modernise javascript test execution with some deps bumps

### PR DESCRIPTION
**Pull request by kevindew**
The bulk of this PR swaps the running of the jasmine tests from being a homebrew implementation with an old version of Jasmine to the use of Jasmine 3 via [Jasmine Gem](https://github.com/jasmine/jasmine-gem).

Doing this has unblocked updating to [govuk_app_config](https://github.com/alphagov/govuk_app_config) 1.3 - so the logstasher stuff has been removed and the unicorn config updated.

Finally in a different approach to https://github.com/alphagov/content-tagger/pull/642 I've added foreman to run the app in docker environment via installing it as a gem in a dockerfile which is the approach recommended by foreman - I'm going to be evaluating if this works out easier than adding it to gemfiles or not.

This will need rebasing when https://github.com/alphagov/frontend/pull/1403 is merged - or vice versa if this goes first.

/cc @sihugh

### CODE REVIEW

**Comment by sihugh** [comment]
This is cool, I've closed https://github.com/alphagov/frontend/pull/1403 in favour of this

**Comment by kevindew** [comment]
@sihugh cool cool - fancy giving it a review too?

**Comment by sihugh** [comment]
I meant to this morning, was going to checkout the CI results and got sidetracked by a squirrel.  I'll look now

**Comment by kevindew** [comment]
Thanks @sihugh 👍

**Pull request merged**
