### PR TITLE
Add Autumn statement promo

### PR DESCRIPTION
**Pull request by jackscotti**
What it will look like:

screen shot 2015-11-20 at 15 06 49

Zendesk:
https://govuk.zendesk.com/agent/tickets/1194049

### CODE REVIEW

**Comment by fofr** [comment]
The image is 200kb, which feels a bit big. Putting it through https://compressor.io/ (or your lossless image compression tool of choice) reduces it to 50kb.

**Comment by jackscotti** [comment]
I had already pushed that through `imageoptim`. I tried using yours but with the loseless algorithm I do not get any dimension reduction:

screen shot 2015-11-20 at 15 31 40

**Comment by jackscotti** [comment]
Add a chat in real life with Paul and we decided to go for the lossy algorithm. The image now is ~50KB.

**Comment by alextea** [comment]
@jackscotti ImageOptim only does lossless compression, so won't have much effect on jpegs. You need to go into the preferences and enable lossy compression (80% is usually good enough and gives you a 42K image in this instance).

**Comment by fofr** [comment]
:+1: This is good to merge on Monday.

**Pull request merged**
