### PR TITLE
[DO NOT MERGE BEFORE 20 Feb] Homepage: add Marriage Allowance promo

### PR DESCRIPTION
**Pull request by benilovj**
This replaces the "Keep warm this winter" promo.

image

- [x] 2i review done by John Oates

### CODE REVIEW

**Comment by edds** [comment]
Can you convert this image to a JPG and reduce the quality. You should be able to lose at least half the file size of that image quite easily.

**Comment by benilovj** [comment]
@edds done - the image is now JPG and 47KB.

**Comment by edds** [comment]
Any chance you could push it down even further? Having a quick go at dragging the quality slider down in Preview.app and using [ImageOptim](https://imageoptim.com/) it should be able to get down below 25KB without much/any visual degradation.

**Comment by benilovj** [comment]
@edds done as suggested, it's now 20KB

**Comment by edds** [comment]
:+1: Thank you @benilovj that is much smaller. Good work.

**Comment by rooreynolds** [comment]
:+1:

**Pull request merged**
