### PR TITLE
Remove make-a-sorn custom slug

### PR DESCRIPTION
**Pull request by brenetic**
`make-a-sorn` was previously a custom slug with a hard corded html
template. This removes all the custom code associated with that which
makes it fall back to a regular transaction. There is already a start
now page for `make-a-sorn` in Publisher.

# Before

before

# After

after

[Trello card](https://trello.com/c/IkNiy7qi/410-convert-make-a-sorn-start-page-into-a-standard-start-page)

cc @keithiopia

### CODE REVIEW

**Comment by h-lame** [comment]
It's all 🔴 ! Big 👍 for delete-only PRs :)

**Comment by h-lame** [comment]
On closer inspection it also looks to do the correct thing.  Happy to merge once we get the ok from content that the new version of the make-a-sorn document has been published.

**Comment by brenetic** [comment]
This is waiting on the ok from either @keithiopia or John Ploughman in the content team before merging.

**Comment by brenetic** [comment]
New make-a-sorn page will be published 5th July. This PR is now ready for merging

**Pull request merged**
