### PR TITLE
Add a `/random` route that redirects to a random page on GOV.UK

### PR DESCRIPTION
**Pull request by issyl0**
- Based on https://github.com/issyl0/govuk-random-page - if Wikipedia
  can have a random page link, why can't we? It will allow people to
  find out about stuff that they may never normally find out about.
- I was going to add a link to the footer for ease of repeatedly
  finding random pages, but that might be too prominent.

:fire:

### CODE REVIEW

**Comment by edds** [comment]
Will this work as expected in production? Will the CDN cache the redirect and there will only be a random page every 30 mins?

**Comment by alext** [comment]
Without setting explicit cache headers, there will be a default cache TTL applied at the CDN.

But, that's all moot because there's nothing to create any routes to allow requests to reach this endpoint.

**Comment by bradleywright** [comment]
I think sorting the entire list of GOV.UK pages in memory might be a bit intensive. It would be easier to add a `/random` endpoint to content API or similar and fetch a single page from that, where the random slice could be done in the database.

**Comment by issyl0** [comment]
Oh, I hadn't thought about caching. What do you mean, @alext?

**Comment by issyl0** [comment]
@bradleywright It only searches the one random page number's content in memory (500 items), not everything. :-\

**Comment by KushalP** [comment]
@issyl0 I think what @alext means here is that there's no _exact_ route being registered with the router for `/random`: https://github.com/alphagov/frontend/blob/master/lib/tasks/router.rake#L14-22

**Comment by issyl0** [comment]
@alext, @KushalP: Done.

**Comment by issyl0** [comment]
:question:

**Comment by fatbusinessman** [comment]
I like this. I would like to see it go live on GOV.UK. I think there are a couple of things we’d need to consider before we can launch it:

* This will always get the artefact list from `www.gov.uk/api` (i.e. the production environment), even when it’s in preview or staging. This could potentially mean we try to redirect to something that doesn’t exist in preview or staging. I don’t think that’s a big problem, but we may be able to work around it using the [content API adapter](https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/content_api.rb).
* We’re planning to replace the content API at the proverbial Some Point, and its replacement may no longer make support grabbing a random page. In the worst case, we may have to remove this functionality at that point; I don’t think that should stop this going live now.

And here’s the big one:

* There aren’t any tests; even with something that’s just for fun, I don’t think we can put it into production without some test coverage. I’m happy to work with you on this, @issyl0.

How does that sound?

**Comment by issyl0** [comment]
@fatbusinessman Thanks. Tests: yes, absolutely - I gave it a go at first, but wasn't very successful. If we could work together on this (and I don't know anything about the content API adapters...), that'd be good.

**Comment by issyl0** [comment]
Having paired with @fatbusinessman, there's now a test for this. :palm_tree:

**Pull request merged**
