### PR TITLE
Update homepage promo box

### PR DESCRIPTION
**Pull request by alex-ju**
Replace "NHS long-term plan" with "Coronavirus: latest information and advice"

### Preview
homepage-update-coronavirus

[Zendesk Ticket](https://govuk.zendesk.com/agent/tickets/3905139)

### CODE REVIEW

**Comment by vanitabarrett** [comment]
@alex-ju Can we delete nhs-long-term-plan.png

**Comment by alex-ju** [comment]
@vanitabarrett I wasn't sure if we're going to need to revert back to it. I can remove all the other ones too

**Comment by vanitabarrett** [comment]
Ah ok, let's leave it for now then! 👍

**Comment by alex-ju** [comment]
It will still be in git history though. It's worth reviewing them all – will make a note.

**Pull request merged**
