### PR TITLE
Remove external-link-tracker interstitial redirect

### PR DESCRIPTION
**Pull request by boffbowsh**
All external links are now tracked using techniques implemented in
govuk_frontend_toolkit such as sendBeacon.

### CODE REVIEW

**Comment by rboulton** [comment]
Thanks for doing this!

**Comment by bradwright** [comment]
You also need to remove the [recommended-links implementation](https://github.com/alphagov/recommended-links/blob/master/lib/tasks/deploy_links.rake#L14)

**Comment by boffbowsh** [comment]
Yarp, currently unpicking that, thanks :)

**Comment by boffbowsh** [comment]
Removed in https://github.com/alphagov/recommended-links/pull/53

**Comment by jamiecobbett** [comment]
:heart:

**Comment by jamiecobbett** [comment]
I think the yml file was missed: https://github.com/alphagov/frontend/pull/887

**Pull request merged**
