### PR TITLE
Replace the homepage 'find a job' image

### PR DESCRIPTION
**Pull request by mgrassotti**
The picture for the ‘Find a job’ feature box on the GOV.UK homepage needs replacing because DWP no longer have permission to use the current image.

Trello: https://trello.com/c/CapOXzTi/682-govuk-homepage-image-replacement

Zendesk: https://govuk.zendesk.com/agent/tickets/2254085

## Before
screen shot 2017-07-19 at 13 22 32

## After
screen shot 2017-07-19 at 13 22 10

### CODE REVIEW

**Comment by cbaines** [comment]
It would be good to get some information about this change in the commit message. Questions that come to my mind are:
 - why is the change being made?
 - where does the new image come from?

**Comment by mgrassotti** [comment]
@cbaines sorry I forgot to add the Trello link

**Comment by cbaines** [comment]
> @cbaines sorry I forgot to add the Trello link

That is useful, but I think its still beneficial to have all the information in the commit message (this opinion is even in the [styleguide](https://github.com/alphagov/styleguides/blob/master/git.md#links-to-issue-trackers)).

**Comment by mgrassotti** [comment]
👍 @cbaines is that ok now?

**Comment by cbaines** [comment]
I'll leave it to someone who has actually looked at this working to approve though, as I think it definitely deserves some testing.

**Comment by mgrassotti** [comment]
@cbaines yes I noticed the different size, but I didn't resized it because I read in the Zendesk ticket that it was specifically requested with that size

**Comment by cbaines** [comment]
> @cbaines yes I noticed the different size, but I didn't resized it because I read in the Zendesk ticket that it was specifically requested with that size

Yeah, and bigger might be better, just need to check that it doesn't make anything worse (e.g. the page layout).

I've got it working locally, and I'll have a quick check in a minute.

**Comment by mgrassotti** [comment]
@fofr is it ok now?

**Comment by mgrassotti** [comment]
There is a strange error making the CI build failing: ```Push event to branch find-a-job-image-replacement
10:51:05 Connecting to https://api.github.com using govuk-ci/****** (GitHub token for govuk-ci with username)
Obtained Jenkinsfile from b0dd251b68c5086c117cc976207af0b66ff3e5e0
[Pipeline] node
Running on ci-agent-4 in /var/lib/jenkins/workspace/ind-a-job-image-replacement-YCCL3ET3M652QWKHJFWD2E5CDZ36MRICANYQT2OHUNWCGW6YC6RA
[Pipeline] {
[Pipeline] load
[Pipeline] // load
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

hudson.remoting.ProxyException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 198: expecting ')', found 'stage' @ line 198, column 7.
         stage("End-to-end tests") {
         ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:360)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:145
[...]```

**Comment by ikennaokpala** [comment]
@mgrassotti I believe that is temporary.. the build and test are now running again

**Comment by fofr** [comment]
@mgrassotti Can you include a screenshot of this in context on the homepage?

Otherwise :+1:

**Comment by mgrassotti** [comment]
@fofr 👍 done!

**Pull request merged**
