### PR TITLE
Add promotion for March 2016 Budget to homepage

### PR DESCRIPTION
**Pull request by erikse**
Zen ticket: https://govuk.zendesk.com/agent/tickets/1257975

Replace the find a job promotion on the homepage with a promotion for the March 2016 Budget which is being published on the 16th.

## Expected changes
[URL on gov.uk](https://www.gov.uk)
 * Removes promotion "Find a job"
 * Adds promotion "March 2016 Budget"

### Before
screen shot 2016-03-09 at 10 48 00 am

### After
screen shot 2016-03-09 at 10 48 49 am

### CODE REVIEW

**Comment by erikse** [comment]
The release date for this has been moved to the 14 March 2016, have updated description accordingly.

**Comment by erikse** [comment]
This is now ready for review/merge for deployment at 4pm

**Comment by dsingleton** [comment]
It'd be worth optimising the image, at 124k it's a little bigger than we'd normally include.

Otherwise LGTM and i'm happy to merge once the image is updated. :+1:

**Comment by dsingleton** [comment]
New image is :+1: 

@erikse: The build failure looks unrelated to the change, so once that's resolved i'd be happy for you to self-merge

**Pull request merged**
