### PR TITLE
Change Agencies and other public bodies count to 408

### PR DESCRIPTION
**Pull request by huwd**
## Problem

Peek 2020-12-08 15-34

## Fix
Update the number again

### CODE REVIEW

**Review by kevindew — APPROVED** [review]
Oh my, it's bonkers we do this manually. Nice one for fixing. Should we record an issue on this repo for it?

**Comment by sihugh** [comment]
> Oh my, it's bonkers we do this manually. Nice one for fixing. Should we record an issue on this repo for it?

Replace the number with "Lots of the"?

**Review by injms — APPROVED** [review]

**Comment by huwd** [comment]
@kevindew This is basically my personal hobby now...

- https://github.com/alphagov/frontend/pull/2494
- https://github.com/alphagov/frontend/pull/2446
- https://github.com/alphagov/frontend/pull/2419
- https://github.com/alphagov/frontend/pull/2280
- https://github.com/alphagov/frontend/pull/2202
- https://github.com/alphagov/frontend/pull/2183
- https://github.com/alphagov/frontend/pull/2079

But yeah I think it is time to do something about it. I'll create a tech debt ticket and put my face on it?

**Comment by huwd** [comment]
@sihugh, @benthorner actually raised this point last time it came up.
Before we go making this page do fancy stuff speaking to organisations listing etc... perhaps we should ask if the User Need this number served is still worthwhile?

**Pull request merged**
